# Site settings
title:          教育研究笔记
description:    "Notes of educational research, a private website"
baseurl:        ""
url:            "http://ner.mowchan.me"

# Google Analytics
# google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         MowChan
  url:          https://ner.mowchan.me/
  email:        mowchann@outlook.com

# Build setting
timezone:       Asia/Shanghai
highlighter:    rouge
markdown:       kramdown
include:
  - _pages

kramdown:
  math_engine: katex
  syntax_highlighter: rouge
  parse_block_html: true
  input:       GFM

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  - jekyll-archives
  - jekyll-toc
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

# Permalinks
permalink:      /:categories/:slug.html
paginate:       10
paginate_path:  archives/:num"

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
# disqus:         jekyll-tale